---
AWSTemplateFormatVersion: "2010-09-09"
Description: Setup to run fargate tasks that can be managed with SSM.
Resources:
  SSMFargateTaskIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole 
  FargateExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPullImagesFromECR
            Effect: Allow
            Action: 
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - logs:CreateLogStream
              - logs:PutLogEvents
              - secretsmanager:GetSecretValue
              - kms:Decrypt
            Resource: '*'
  ecsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "ecsTaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - !Ref FargateExecutionPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Outputs:
  SSMFargateTaskIAMRole:
    Description: The ARN of the role for Fargate Tasks to run in.
    Value: !GetAtt SSMFargateTaskIAMRole.Arn
  ecsTaskExecutionIAMRole:
    Description: The ARN of the role for the ecs cluster.
    Value: !GetAtt ecsTaskExecutionRole.Arn