
---
AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repo to house container images.
Parameters:
  ServiceName:
    Type: String
    Description: A name for the service
  ImageUrl:
    Type: String
    Description: The url of a docker image that contains the application process that
                 will handle the traffic for this service
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding to
  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run
  TaskRoleArn:
    Type: String
    Default: ""
    Description: (Optional) An IAM role to give the service's containers if the code within needs to
                 access other AWS resources like S3 buckets, DynamoDB tables, etc
  ExecutionRoleArn:
    Type: String
    Default: ""
    Description: (Optional) An IAM role to give the service's containers if the code within needs to
                 access other AWS resources like S3 buckets, DynamoDB tables, etc
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'ServiceName'
      Cpu: !Ref 'ContainerCpu'
      Memory: !Ref 'ContainerMemory'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskRoleArn
      TaskRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: !Ref 'ServiceName'
          Cpu: !Ref 'ContainerCpu'
          Memory: !Ref 'ContainerMemory'
          Secrets:
            - Name: "KSUB_SECRET_KEY"
              ValueFrom: "arn:aws:secretsmanager:ap-southeast-2:392008160963:secret:ksub/uat/KSUB_SECRET_KEY-xyfrSn"
            - Name: "KSUB_EMAIL_URL"
              ValueFrom: "arn:aws:secretsmanager:ap-southeast-2:392008160963:secret:ksub/uat/KSUB_EMAIL_URL-4pUeRh"
          Image: !Ref 'ImageUrl'
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
          LogConfiguration:
            LogDriver: awslogs
            Options: 
              awslogs-group: "/ecs/ssm-agent"
              awslogs-region: "ap-southeast-2"
              awslogs-stream-prefix: "ecs"